version: '3.7'

services:
  assignment-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/crontab.txt:/crontab.txt
      - ./certs/conf:/etc/letsencrypt
      - ./static:/static:rw
      - ./frontend/front_dist:/front_dist