version: '3.7'

services:

  assignment-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - assignment-backend
    command: npm run dev
    ports: 
      - 8060:8060
    restart: always
    volumes:
      - ./frontend:/frontend:rw
      - ./frontend/front_dist:/frontend/front_dist:rw
      - /frontend/node_modules
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  assignment-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      assignment-db:
        condition: service_healthy
    ports: 
      - 8070:8070
    restart: always
    command: nodemon app.js
    volumes:
      - ./backend:/backend:rw
      - ./backend/dist:/backend/dist:rw
      - /backend/node_modules
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      JWT_SECRET: "${JWT_SECRET}"
      DB_HOST: "assignment-db"

  assignment-db:
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    expose: 
      - 3306
    volumes:
      - assignmentDB:/assignmentDB/db
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 5s
      retries: 10

  assignment-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - assignment-frontend
      - assignment-backend
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static:rw
      - ./frontend/front_dist:/front_dist

volumes:
  assignmentDB: